### ISSUE TITLE
Using keyword arguments as part of interface

### ISSUE THREAD

**Issue by darsnack** [JuliaReinforcementLearning/CommonRLInterface.jl#16]
This came up in #8, but it is a more general question. Do we want to use keyword arguments as part of the interface? I personally think there is a middle ground on this issue.

Pros:
- Keyword arguments reduce the total # of functions. I think we should strive to be as concise as possible.
- Keyword arguments can be intuitive. For example, in #8, I think of `valid_actions` as filtering `actions(env)` based on the dynamic state. It seems more natural to call `actions(env; valid = true)` because I'm asking for the same set w/ an optional filter tacked on.

Cons:
- Trying to squish lots of functions into a single function with keywords is also confusing. I would say at most 1-2 keyword arguments is sensible.
- The `provided` mechanism may not work with keywords
- Forcing the environment writer to do too much within a single function

Personally, I am interested in allowing keywords for the sake of readability. In cases where they cause confusion, I'd prefer splitting into two functions.

**Comment by zsunberg** [comment]
Ok, I did some investigation, and it is technically possible to support keyword arguments with `provided`, and there would be no change to the simple use cases.  Some advanced use cases would become trickier, but it is not a dealbreaker.

**Comment by jonathan-laurent** [comment]
Another factor to consider is that merging several functions into a single function with keyword arguments removes the possibility for the client to only implement a subset of these functions.

It also complicates the story for defaults (which we haven't figure out yet). Indeed, if we have either a `valid_actions_mask` (as I advocate in https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/19) or an `is_valid` function, then a reasonable default implementation can be provided for `valid_actions`.

Personally, I tend to think that the cons outweigh the pros:

- I do not think reducing the number of functions should be a goal per se (as opposed to reducing the number of concepts, as @zsunberg mentions in an other post).
- I think preferring `actions(env; valid = true)` to `valid_actions(env)` is mostly a matter of taste. I would concede one objective argument in favor of the keyword style, which is that it becomes impossible for the user to mistakenly write `actions(env)` instead of `valid_actions(env)`: the keyword style forces you to think about whether or not you want to filter out invalid actions every time you type `actions`. That being said, this is a problem that can be solved with good documentation.

**Comment by darsnack** [comment]
> removes the possibility for the client to only implement a subset of these functions.

This is a very good point that I had not considered. I think if it is possible to support keywords with `@provide`, then we should add it for future use cases. But at least for the current set of proposed functions, I am now convinced separate functions is better.

**Comment by zsunberg** [comment]
One technical note: I just did a little more investigation, and I do not currently know a way to make *provided* compile away with keyword argument *types*, so, if an environment writer implemented
```julia
@provide f(x::Int, a::Int=1)
```
then `provided(f, 1, a="a string")` would have to return true to be efficient. This might be a significant difficulty.

Overall, I like just using functions better, but, it is tempting to start thinking about tings like `setoption!(env, observation_type=Vector{Float64}` that would require keywords.

**Comment by zsunberg** [comment]
For now, we will not use keyword args in the interface, but we might reconsider this for the future.
