### ISSUE TITLE
Support for multiple players games

### ISSUE THREAD

**Issue by jonathan-laurent** [JuliaReinforcementLearning/CommonRLInterface.jl#20]
How should we support multiple-player games?

I think a good starting principle is that support for multiple-player games should not impact the interface for standard, one-player RL environments. A user that isn't interested about this part should be able to ignore it completely. Therefore, I think we should only propose adding functions and not modify the behavior of existing ones.

Another question is: what kinds of multiple player games do we want to support? I think that supporting two-players, sequential, zero-sum games is a no brainer as most RL algorithms can be trivially extended to support these games. For more complicated games, I think it is open to debate.

**A starting point:**

There should be a `current_player(env)` function but what should it return? An integer between `1` and `num_players(env)`?

**Comment by zsunberg** [comment]
> multiple-player games should not impact the interface for standard, one-player RL environments.

Yes, I think this would greatly reduce the understanding burden.

Is the multiplayer case different enough that we should have a different package for it? This separate package could use some of the same concepts as CommonRLInterface and contain some of the same functions, but the documentation and core interface could be completely focused on multiplayer.

**Comment by jonathan-laurent** [comment]
I feel that two-players, sequential, zero-sum games are similar enough to be included in this package.
Also, most RL algorithms can be adapted trivially to work with such games.

The question is trickier for more complicated games.

Edit: And of course, AlphaZero.jl provides a clear use case for adding support for two-players, sequential, zero-sum games. :-)

**Comment by MaximeBouton** [comment]
Do you consider multiagent problems as part of this category? 
I think support for multiagent problems should be added otherwise.

**Comment by jonathan-laurent** [comment]
> Do you consider multiagent problems as part of this category?
> I think support for multiagent problems should be added otherwise.

To be honest, I am not a specialist in multiagent problems and maybe the best solution to see whether or not support should be included is to draft a proposal and then decide whether or not it should go in a separate package.

**Comment by MaximeBouton** [comment]
sounds good, I will open another issue regarding this specific aspect

**Comment by jonathan-laurent** [comment]
Here are proposals for adding support to sequential, multiplayer, zero-sum games.
Note that I am only trying to get the API structure right here and specific function names should be debated.

**Proposal A1**

* We define an enumeration `@enum Player MaximizingPlayer MinimizingPlayer`. As the names should suggest, `MaximizingPlayer` is attempting to maximize the reward given by the environment and `MinimizingPlayer` is attempting to minimize it.
* We add a `player(env) :: Player` function to query which player is expected to play next.
* We add a `two_players(env) :: Bool` function that indicates whether or not a game has a minimizing player. If `two_players(env) == false`, then we must have `player(env) == MaximizingPlayer`.

**Proposal A2**

* We add a `minimizing_player(env) :: Bool` that returns whether or not the minimizing player is about to play.
* We add a `has_minimizing_player(env) :: Bool` function that returns whether the current game has a minimizing player.

**Proposal B**

In proposal A above, we restrict ourselves to two-player games and assume that a two-player game always involves exactly one maximizing player and one minimizing player. We can relax this assumption while still working in the zero-sum setting:

* Players are given integer identifiers from 1 to n
* The `current_player(env)` function returns an integer from 1 to n
* The `players(env)` function returns a list of n `PlayerType` where `@enum PlayerType MaximizingPlayer MinimizingPlayer`

This allows a natural description for games where several players can collaborate for example. However, strictly speaking, this does not add any expressiveness as a two-players game with perfect information where both players are collaborating can be expressed as a single-player game where the state indicates which player must play next and the user policy can do some dispatching based on this information.

**Non zero-sum games**

Proposal B could be further generalized to allow non zero-sum games. However, this would probably complicate the rest of the API as there is now a need for multiple rewards channels. Also, algorithms for such multi-agent systems are usually pretty different from standard RL algorithms and so the need for a common RL interface arguably becomes less pressing. The same could be argued about supporting non-sequential games.

Once again, the main argument for supporting two-players, zero-sum games is that most RL algorithms can be trivially adapted to accommodate this case. In particular, all that is needed for MCTS to support such games is literally two new lines of code.

**Comment by zsunberg** [comment]
I don't have much experience with games, so I am not too confident in evaluating this. Here are two other suggestions (not necessarily what I think is best):

#### Proposal C

Add a single function `optimization_sense(m)` that returns `1` or `-1` depending on whether the current player should be maximizing or minimizing the reward for that step.

#### Proposal D

Since a game is fundamentally different from an optimization problem, we introduce new abstract types:

`AbstractSingleplayerEnv` or just `AbstractEnv`: Single player environment that represents an MDP or POMDP
`AbstractZeroSumEnv`: Two player environment with a single reward signal. Player 1 tries to maximize, Player 2 tries to minimize. 

And then later, we could add `AbstractMultiplayerEnv`

I think it will be more natural to think of these cases separately and have some differences in the interfaces. I think algorithm-writers will have to consciously think about which type of environment they will support, so I don't think it is bad to introduce these types (and it is not too difficult to write `const SupportedEnv = Union{AbstractMultiplayerEnv, AbstractEnv}` if you have code that supports multiple types of environment.

To facilitate experimentation between multi-agent algorithms and single-agent algorithms that attempt to directly learn the optimal joint action, we could provide `convert(::Type{AbstractEnv}, ::AbstractMultiplayerEnv)`.

-----

I guess I think I like proposal D the best, followed probably by something like A1.

Also, I'm curious: does everyone agree that "most RL algorithms can be trivially adapted to accommodate this case". (I'm not doubting @jonathan-laurent :smile: - just curious because I have not done much with games)

**Comment by jonathan-laurent** [comment]
> Also, I'm curious: does everyone agree that "most RL algorithms can be trivially adapted to accommodate this case".

Maybe I can refine this statement a little bit. The "theoretical" justification is that most RL algorithms rely on a variant of the Bellman equations and these equations generalize very well to the two-player zero-sum case (just replace max by min depending of who is playing). In particular, MCTS, policy iteration, value iteration and Q-learning can be adapted to the two-players, zero-sum setting by merely adding two lines of code.

Admittedly, there are also some practical differences to take into account sometime. In particular, when using Deep-RL methods, you may want to take special measures to ensure that one player won't overfit against a single line of play at each iteration, but even this has more impact on the choice of the algorithm itself than on how it is implemented.

In AlphaZero.jl, the only place where I make a special case for two-player environments is when testing a new-generation network to check whether or not it is really better than its predecessor and should be used instead for generating data.

- In a single-player environment, one could probably just compare the average reward obtained by the new and old network on a series of games, or even skip this step altogether.
- In the case of zero-sum, two-player games that are also symmetric (the rules are the same for both players), one can do something smarter: playing a series of games opposing the new network to the old one.

> I guess I think I like proposal D the best, followed probably by something like A1.

I am not completely opposed to adding a new abstract type for two-player, zero-sum games but I think this should only be done if we can fulfill the following guarantees:

- It should not cause any significant duplication, both in the source code of CommonRLInterface.jl and in the documentation.
- `AbstractSinglePlayerEnv` and `AbstractZeroSumEnv` must evolve together in the sense that any feature added to one of them should be automatically available to the other (as long as it makes sense).

**Comment by zsunberg** [comment]
> - It should not cause any significant duplication, both in the source code of CommonRLInterface.jl and in the documentation.
> - AbstractSinglePlayerEnv and AbstractZeroSumEnv must evolve together in the sense that any feature added to one of them should be automatically available to the other (as long as it makes sense).

Yes, totally agree with this!

> The "theoretical" justification is that most RL algorithms rely on a variant of the Bellman equations and these equations generalize very well to the two-player zero-sum case (just replace max by min depending of who is playing). In particular, MCTS, policy iteration, value iteration and Q-learning can be adapted to the two-players, zero-sum setting by merely adding two lines of code.

Right - I think this is a very important point, and justification for why we should give special consideration to zero-sum two-player games.

On a somewhat related note, I spent some time perusing the [Open Spiel description](https://arxiv.org/pdf/1908.09453.pdf), and I think that will be really useful when we develop a general multiplayer interface.

After thinking about it, I am more convinced that we should have several abstract environment types. Trying to squeeze MDPs and games into a single type just puts too much cognitive load on algorithm writers. If there is just one `AbstractEnv`, when they are implementing their algorithm, they have to think about "what if it's a multiplayer game?" and handle all possibilities. If we have multiple types, they can think about them separately, and, if it turns out that the same code will work on many types, they can just use a `Union`.

For now, I propose
```
abstract type AbstractMarkovEnv <: AbstractEnv end        # Represents an MDP or POMDP
abstract type AbstractZeroSumEnv <: AbstractEnv end     # Represents a *two-player* *zero sum* game, where players have distinct turns, one after the other. Player 1 attempts to maximize the reward, player 2 attempts to minimize it.
```

Some important questions/remarks:
1. Should we mandate that play alternates between players (1, 2, 1, 2, 1, 2,...) (as currently written in the comment above), or should there be a `player(env)` function that indicates the current player? (or both, or should we wait until the multi-agent environment is designed)
2. If play proceeds with alternating calls to `step!(env, a)` for each player, the observation returned should be received by the player *who will take the next action*. This could be a source of major confusion.
3. Does `actions(env)` return the union of the action spaces of the two players, or do we need `actions(env::AbstractZeroSumEnv, player::Integer)`? We could also just use `valid_actions` for this.

What do people think?

**Comment by findmyway** [comment]
> 1. Should we mandate that play alternates between players (1, 2, 1, 2, 1, 2,...) (as currently written in the comment above), or should there be a player(env) function that indicates the current player? (or both, or should we wait until the multi-agent environment is designed)

I'd prefer to have a `player(env)` first.

> 3. Does actions(env) return the union of the action spaces of the two players, or do we need actions(env::AbstractZeroSumEnv, player::Integer)? We could also just use valid_actions for this.

`actions(env::AbstractZeroSumEnv, player::Integer)` would be more clear to me.

**Comment by jonathan-laurent** [comment]
> 1. Should we mandate that play alternates between players (1, 2, 1, 2, 1, 2,...) (as currently written in the comment above), or should there be a player(env) function that indicates the current player? (or both, or should we wait until the multi-agent environment is designed)

No, it is important to allow the same player to play several times in a row. This appears naturally in many games such as checkers, mancala...

> 2. If play proceeds with alternating calls to step!(env, a) for each player, the observation returned should be received by the player who will take the next action. This could be a source of major confusion.

I agree this is confusing. To be honest, having `step!` return an observation never made sense to me, at least in the setting of perfect information environments (things are different for POMDPs I suppose). I think it is more intuitive to manually query the state before taking an action.

**Here is an idea: how about we modify `step!` to return a named tuple instead of a tuple?** This way, it is not mandatory to return an observation and the convention should be that `ZeroSumEnv` environments must never produce observations.

> Does actions(env) return the union of the action spaces of the two players, or do we need actions(env::AbstractZeroSumEnv, player::Integer)? We could also just use valid_actions for this.

I think both should be provided. I think there is an important class of games that might be called "symmetric" where the rules (and therefore action spaces) are the same for both players. We should add a trait for this at some point. And for those games, it would also make sense to just call `actions(env)`.

**Comment by zsunberg** [comment]
Thanks for the discussion! Ok, it seems like we should definitely have `player` and not require alternating play.

> I agree this is confusing. To be honest, having step! return an observation never made sense to me, at least in the setting of perfect information environments (things are different for POMDPs I suppose). I think it is more intuitive to manually query the state before taking an action.

Ok, I think this is actually a really good reason for having `observe` be separate from `step!` (#12).

> Here is an idea: how about we modify step! to return a named tuple instead of a tuple?

Providing multiple ways to do the same thing can result in a lot of mental work for an algorithm to properly handle every case.

In light of this, I am actually favoring going to a different required core interface (I know I resisted this earlier, but I think the reason above is a good one :smile: ):
```
reset!(env)     # returns nothing
act!(env, a)    # returns reward, done, and info
observe(env) # returns the observation (for the current player in an AbstractZeroSumEnv)
actions(env)    # returns the set of all possible actions for the environment
```

I think for the MDP/POMDP case, this makes sense with the classic "observe-act" loop. For `AbstractZeroSumEnv`, we will have an additional required function, `player

> I think both should be provided.
> actions(env::AbstractZeroSumEnv, player::Integer) would be more clear to me.

Ok, we will add an optional `actions(::AbstractZeroSumEnv, ::Integer)` function.

What do people think? I will try to make a PR for this soon.

**Comment by jonathan-laurent** [comment]
@zsunberg I think this is a great proposal.

Regarding `act!`, what about not returning a `done` boolean flag and adding a `terminated(env)` function?

Indeed, I would advocate that:

* Given an environment, one should be able to tell whether or not it is in a terminal state without relying on any piece of context. Therefore, `terminated` is needed anyways.
* In the presence of `terminated`, there is no need for `act!` to return a flag.
* In general, I think that `act!` should only return objects that are properties of the transition step itself and not of its endpoint states. This is the case for `reward` and `info` but not for `done`.

**Comment by zsunberg** [comment]
I would be ok with `terminated(env)`. Would it be optional or required? I think optional. What do others think?

I think in this case we should also consider just getting rid of the info return and having `act!` return only a reward. Info is really only useful for debugging environments, and I don't think solvers should rely on it.

**Comment by jonathan-laurent** [comment]
I fully agree with you.

- I think `act!` should only return a reward.
- We could make `terminated` optional on the basis that this info could potentially be deduced from the state.

**Comment by jbrea** [comment]
I like the direction this is taking! But do you really think it is necessary for `act!` to return a reward? First, like `observe(env)` and `terminated(env)` I think it would make sense to have a function `observe_reward(env)` and have `act!` return `nothing`. This gives more flexibility, e.g. when you want to train on a clipped reward and track the unclipped reward for evaluation (currently we do this with [`RewardOverriddenObs`](https://github.com/JuliaReinforcementLearning/ReinforcementLearningBase.jl/blob/9e7281ccda9efd63f2b6b12b663cba393b50a279/src/implementations/observations.jl#L82)). Optionally, an environment author could make sure that an algorithm gets zero additional reward if `observe_reward(env)` is called multiple times between different `act!`. Second, when I don't look through my POMDP-glasses, I find it more natural to think of the reward as a special kind of observation and `act!` as a command that doesn't return anything. Of course, in some environments the reward depends not only on the current state of the environment but also on how it is reached and thus it may be puzzling to get in such cases potentially different results for `observe_reward(env)` while getting the same result for `observe(env)`.

**Comment by jonathan-laurent** [comment]
I think @jbrea makes a pretty good case for not having `act!` return rewards.

This leaves one question though: what should `observe_reward` return when called at an initial state before any transition happened. Should it return `0`? Should it return `nothing`? Should it be unspecified?

**Comment by zsunberg** [comment]
`r = act!(env, a)` definitely *feels* better to me because rewards result from taking an action in the environment, but I'll try to figure out if that feeling is rooted in a concrete objective reason or not :smile: . 

To me, the biggest advantage of `r = acts!(env, a)` is that it clears up ambiguity about the order of a simulation loop and terminal rewards. For instance
```julia
while !terminated(env)
    o = observe(env)
    reward_sum += reward(env)
    act!(env, policy(o))
end
```
is (badly) incorrect if there is a terminal reward. Of course we can document that `reward` *must* be called *after* every call to `act!`, but it seems better to enforce this in code.

Another small advantage is that it keeps the list of required functions smaller. (this should not be an overriding concern, but I think it is worth considering)

> This gives more flexibility, e.g. when you want to train on a clipped reward and track the unclipped reward for evaluation (currently we do this with RewardOverriddenObs)

Can you explain how RewardOverridenObs is used or point to an example? Who uses it? A problem writer or an algorithm writer or a third party?

> Of course, in some environments the reward depends not only on the current state of the environment but also on how it is reached and thus it may be puzzling to get in such cases potentially different results for observe_reward(env) while getting the same result for observe(env).

This doesn't seem like a huge additional concern to me because `observe`could be the same way, e.g. if the observation is the distance between the current and previous state, so it will have to be dealt with anyways.

> what should observe_reward return when called at an initial state before any transition happened.

This actually doesn't matter at all! :smile: The agent can't affect this reward with its actions, so it will not matter for the optimization problem.

**Comment by jonathan-laurent** [comment]
> To me, the biggest advantage of r = acts!(env, a) is that it clears up ambiguity about the order of a simulation loop and terminal rewards. For instance

This is a pretty good point. One way to disambiguate may be to rename `reward` into last_reward`, although it is slightly verbose.

**Comment by jbrea** [comment]
> because rewards result from taking an action in the environment

(So do next observations.)

In board games, like chess, I am not sure it is the most natural thing to think of rewards as being the result from taking an action: whether a game is a loss or a win is a feature of the state. The game could be ended by a move of mine or by one of my opponent. Even if I do a move that leads to a state where my opponent could immediately win the game, I don't get immediately the (negative) reward upon doing that move, but I can observe the loss after my opponent has effectively done the winning move. 

(Even in classical POMDP settings I think it is often possible to have two views on reward, e.g. in the TigerPOMDP you can see it as either getting punished for opening the tiger's door or getting punished when the tiger's door is open.)

> Of course we can document that reward must be called after every call to act!, but it seems better to enforce this in code.

Good point. 

> Can you explain how RewardOverridenObs is used or point to an example? Who uses it? A problem writer or an algorithm writer or a third party?

For example in the Atari domain [it is common](https://deepmind.com/blog/article/preserving-outputs-precisely-while-adaptively-rescaling-targets) to train on rewards clipped to [-1, 1] (or do some fancier reward transformation) but report the unclipped rewards. This allows to use the same hyperparameters of the algorithms despite hugely different reward scales of the different games. I guess I would call it the benchmark writer who uses `RewardOverridenObs`. We use it [here](https://github.com/JuliaReinforcementLearning/ReinforcementLearningZoo.jl/blob/master/src/experiments/atari.jl#L15).

**Comment by zsunberg** [comment]
> (So do next observations.)

Yes, this is why I initially pushed for `step!` to return both observation and reward, but I think `observation(env)` returning the observation for `player(env)` is the overriding principle. Additionally, I don't think algorithm-writers will make as many mistakes calling `observe(env)` as `reward(env)` because the algorithm writer will always be looking for the observation to execute a policy, whereas there is nothing making sure the algorithm writer gets the last reward after checking `terminated`.

> In board games, like chess ... has effectively done the winning move.

Note that, as `AbstractZeroSumEnv` is currently defined, the reward returned by `act!` applies to *both* players. Player 1 is just trying to maximize and player 2 is trying to minimize, so players need to care about the rewards from *every* action taken, not just their own.

Regarding `RewardOverridenObs`, it seems like this could just as easily be accomplished with `r = act!(env, a)` with a wrapper of the environment or by the algorithm itself. In the example you pointed to, it looks like you are wrapping the environment anyways. Is there an advantage to `RewardOverridenObs` that I am missing?

I am in favor of `r=act!(env, a)`, because in my experience with POMDPs, making sure every algorithm collects rewards in exactly the same way is fraught. However, I don't think `reward(env)` would sink us. The most important thing is getting a usable version of the interface out. So, let's vote on it:

:rocket:: `r = act!(env, a)`
:tada::`reward(env)` (or a separate function with a different name)

**Comment by MaximeBouton** [comment]
In cases where players would receive different rewards, wouldn't having `reward(env, player)` be useful? 
Maybe in zero sum games it is not needed, but I am thinking about multi agent or multi player environment where each agent would get different reward. 

In the current design, when calling `act!(env, a)`, what is `a`? is it a single player action or a joint action? If it is a single player action then `act!(env, a)` returns the reward associated to that player and it is fine, if it is not, I am a bit confused on what `r` would be...

**Comment by zsunberg** [comment]
Currently, in an `AbstractZeroSumEnv`, only one player, specifically `player(env)` plays at a time, so it is just the action for that player (note that this could be used to model a simultaneous play game as noted in Fact 1 of the openspiel design paper https://arxiv.org/pdf/1908.09453.pdf). Every reward is for *both* players. Player 1 seeks to maximize, Player 2 seeks to minimize (this is why the abstract type has "ZeroSum" in it).

If we were to extend this design to a general multiplayer case, I think `act!` would return a vector of rewards for all players (reward for any agent can come when any other agent is acting). Instead of a `player(env)`, we might have `players(env)` that could indicate that multiple players play at the same time.

If we introduced `reward(env, player)`, would every player get reward at every timestep, or only the player who played?

**Comment by MaximeBouton** [comment]
I think `reward(env, player)` has the same problem as `reward(env)` in terms of not ensuring the simulation order. `reward(env, player)` would return the reward received by `player`. This could be achieved fine by returning a vector or dictionary of rewards in `act!` though.

**Comment by zsunberg** [comment]
I don't think there's a clear objective right answer here, so make sure to vote on your preference [here](https://github.com/JuliaReinforcementLearning/CommonRLInterface.jl/issues/20#issuecomment-655761688). I'll be out of town this weekend, but if we get a few more votes (@jonathan-laurent @jbrea @MaximeBouton ) I'll implement it on Monday.

**Comment by jonathan-laurent** [comment]
@jbrea @findmyway  Just before I vote, can you clarify how having a separate `reward` function adds flexibility? Indeed, in both cases, you can override the reward behavior by defining an environment wrapper. Is your point that having a separate `reward` function makes it more natural to add alternative reward functions such as `clipped_reward`? Can you show me a concrete usecase where the `r = act!(env)` solution would make things more difficult for you?

**Comment by findmyway** [comment]
I think `r = act!(env)` will not make things more difficult for us. With an environment wrapper, there isn't much difference here. We just need to decide which one is more natural. And I second @jbrea 's comment:

> In board games, like chess, I am not sure it is the most natural thing to think of rewards as being the result from taking an action: whether a game is a loss or a win is a feature of the state. The game could be ended by a move of mine or by one of my opponent. Even if I do a move that leads to a state where my opponent could immediately win the game, I don't get immediately the (negative) reward upon doing that move, but I can observe the loss after my opponent has effectively done the winning move.

**Comment by jbrea** [comment]
> whereas there is nothing making sure the algorithm writer gets the last reward after checking `terminated`.

If this is the only concern: what about providing a little test environment that errs when no terminal reward gets collected?

> Every reward is for *both* players. Player 1 seeks to maximize, Player 2 seeks to minimize.

Thanks, this makes sense.

> Can you show me a concrete usecase where the `r = act!(env)` solution would make things more difficult for you?

I don't have a concrete usecase, where this would make things more difficult. So far I don't think it will cause any problems. I like that we can call `r = reward(wrapped_env)` and `original_reward = reward(wrapped_env.env)`, but one can of course also write `r = act!(wrapped_env, a)` and `original_reward = original_reward(wrapped_end)`.

If you feel like `r = act!(env, a)` is the right thing to do, please go ahead. While I prefer `reward(env)`, it doesn't make a big difference for me.

**Comment by zsunberg** [comment]
Ok, cool, thanks for the discussion everyone! Let's go with `r = act!(env, a)`. I'll make the changes tomorrow morning.
