### ISSUE TITLE
Rename CommonEnv to AbstractCommonEnv

### ISSUE THREAD

**Issue by findmyway** [JuliaReinforcementLearning/CommonRLInterface.jl#4]
It would be better to stick with this naming convention.

And use `convert(AbstractCommonEnv, env::YourEnv)`

**Comment by zsunberg** [comment]
Ok, I would be ok with switching to use `Abstract<something>`. Anyone else have any preferences or links to discussions in the docs or on  about naming conventions of abstract types?

I broke the `convert` question out into #5 .

Any other votes?
:+1: = CommonRLEnvironment.AbstractCommonEnv
:tada: = CommonRLEnvironment.CommonEnv
:heart: = CommonRLEnvironment.AbstractEnv

**Comment by zsunberg** [comment]
oh wait, you can only react with a few emojis... hang on

**Comment by zsunberg** [comment]
Ok, I changed my vote, and it seems like we like just `AbstractEnv`. But won't it be annoying if you do
```
using CommonRLInterface
using <any other RL Library>
```
and they both export `AbstractEnv`?

**Comment by mkschleg** [comment]
I think the hope of the CommonRLInterface is to avoid these issues.

In any sense, I don't thing it will matter. What I think will happen is you'll get a warning and you'll have to specify which one you are using if you are defining your own environment. But otherwise things should be ok. Right? Maybe things work differently for Abstract types.

**Comment by zsunberg** [comment]
Yeah, I guess you'll just have to do
```julia
struct MyEnv <: CommonRLInterface.AbstractEnv
```
which is not too bad
