### ISSUE TITLE
Favor separate packages or submodules?

### ISSUE THREAD

**Issue by zsunberg** [JuliaReinforcementLearning/CommonRLInterface.jl#41]
I am planning on adding a few things to this package to assist in my teaching this spring (the first thing is #40 wrappers). One question is should things be organized into submodules, e.g. `CommonRLInterface.Wrappers` or separate packages, e.g. `CommonRLWrappers`?

**Comment by zsunberg** [comment]
It might also be nice to have `CommonRLWrappers.Optional`

**Comment by lassepe** [comment]
I'm a big fan of submodules because they provide a nice way for grouping functionality without adding a lot of  maintenance complexity. In particular, it is really useful if there is a doc-string attached to each submodule so that you can type `?CommonRLWrappers.Optional` to figure out what this submodule has to offer. I have adopted this design patterns for my personal projects where I would typically have a submodule `CoreInterface` and then I have each optional interface extension or convenience implementation in a separate submodule. This way you can can just write in your docs "if you need functionality X, implement the interface of module Y". And if you want to offer a quick way of `using` everything, you can still provide a "toolbox` submodule that just re-exports functionality from various modules. The only annoying thing is that the syntax for including submodules is really ugly.

**Comment by zsunberg** [comment]
Thanks! This is helpful. Let's plan to use submodules.
